version: '3'
services:
    php-apache:
        container_name: php_$ENV
        build: ./
        ports:
            - "127.0.0.1:$WEB_PORT:80"

    mariadb:
        image: mariadb:10.5
        container_name: mariadb_$ENV
        volumes:
            - ../dbs/maria$ENV:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'db'

    myadmin:
        container_name: myadmin_$ENV
        image: phpmyadmin/phpmyadmin
        ports:
            - "127.0.0.1:$MYADMIN_PORT:80"
